version: '2'
services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
        ports:
            - 9200:9200
        volumes:
            - esdata:/usr/share/elasticsearch/data
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            default:
                aliases:
                    - service.elasticsearch

volumes:
    esdata: {}

networks:
    default: {}
